export const introKeyMap = {
  parking: "주차 시설",
  infocenter: "문의 및 안내",
  chkbabycarriage: "유모차 대여",
  restdate: "쉬는 날",
  expguide: "체험 안내",
  chkcreditcard: "신용카드 가능 여부",
  chkpet: "애완동물 동반",
  accomcount: "수용 인원",
  usetime: "이용 시간",
  opendate: "개장일",
  parkingfee: "주차 요금",
  contenttypeid: "관광 타입",
  scale: "규모",
  usefee: "이용 요금",
  discountinfo: "할인 정보",
  spendtime: "관람 소요 시간",
  firstmenu: "대표 메뉴",
  treatmenu: "취급 메뉴",
  packing: "포장 가능 여부",
  traffic: "교통 안내",
  infocenterfood: "문의 및 안내",
  reservationfood: "예약 안내",
  opentimefood: "영업 시간",
  restdatefood: "쉬는 날",
  discountinfofood: "할인 정보",
  chkcreditcardfood: "신용카드 가능 여부",
  kidsfacility: "놀이방",
  opendatefood: "개업일",
  smoking: "금연/흡연",
  roomcount: "객실 수",
  roomtype: "객실 유형",
  refundregulation: "환불 규정",
  checkintime: "입실 시간",
  checkouttime: "퇴실 시간",
  reservationlodging: "예약 안내",
  pickup: "픽업 서비스",
  barbecue: "바비큐장",
  seminar: "세미나실",
  sports: "스포츠 시설",
  karaoke: "노래방",
  publicpc: "공용 PC",
  sauna: "사우나",
  fitness: "피트니스",
  publicbath: "공용 샤워실",
  bicycle: "자전거 대여",
  campfire: "캠프파이어",
  subfacility: "부대 시설",
  foodplace: "식음료장",
  reservation: "예약 안내",
  goodstay: "굿스테이 여부",
  hanok: "한옥 여부",
  benikia: "베니키아 여부",
  saleitem: "판매 품목",
  saleitemcost: "판매 품목 가격",
  fairday: "장날",
  openperiod: "개장 기간",
  shopguide: "매장 안내",
  culturecenter: "문화센터",
  restroom: "화장실",
  infocenterculture: "문의 및 안내",
  parkingculture: "주차 시설",
  usetimeculture: "이용 시간",
  restdateculture: "쉬는 날",
  accomcountculture: "수용 인원",
  chkbabycarriageculture: "유모차 대여",
  chkcreditcardculture: "신용카드 가능 여부",
  chkpetculture: "애완동물 동반",
  parkingfood: "주차 시설",
  lcnsno: "인허가번호",
  eventstartdate: "행사 시작일",
  progresstype: "진행 상태",
  sponsor1tel: "주최자 연락처",
  usetimefestival: "이용 요금",
  sponsor2: "주관사",
  sponsor1: "주최자",
  festivaltype: "축제 유형",
  eventplace: "행사 장소",
  playtime: "공연 시간",
  eventenddate: "행사 종료일",
  infocenterleports: "문의 및 안내",
  chkcooking: "조리 가능 여부",
  parkinglodging: "주차 시설",
  infocenterlodging: "문의 및 안내",
  chkcreditcardshopping: "신용카드 가능 여부",
  opendateshopping: "개장일",
  infocentershopping: "문의 및 안내",
  restdateshopping: "쉬는 날",
  opentime: "영업 시간",
  parkingshopping: "주차 시설",
  chkbabycarriageshopping: "유모차 대여 여부",
  beverage: "음료",
};
